# Generated by Django 5.2.17 on 2026-09-16 11:33

import core.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Installation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('install_id', models.CharField(default=core.models.new_install_id, max_length=64, unique=True, verbose_name='identifiant')),
                ('secret', models.CharField(blank=True, max_length=128, verbose_name='secret')),
                ('public_key_pem', models.TextField(blank=True, verbose_name='clé publique (Ed25519)')),
                ('private_key_pem', models.TextField(blank=True, verbose_name='clé privée (Ed25519)')),
                ('version', models.CharField(blank=True, max_length=20, verbose_name='version')),
                ('enabled', models.BooleanField(default=False, verbose_name='canal activé')),
                ('registered_at', models.DateTimeField(blank=True, null=True)),
                ('last_ping_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('pending_update', models.CharField(blank=True, max_length=20, verbose_name='mise à jour proposée')),
                ('interventions', models.JSONField(blank=True, default=list)),
            ],
            options={
                'verbose_name': 'Installation',
                'verbose_name_plural': 'Installation',
            },
        ),
        migrations.CreateModel(
            name='SchoolYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=32, unique=True, verbose_name='libellé')),
                ('start_date', models.DateField(verbose_name='début')),
                ('end_date', models.DateField(verbose_name='fin')),
                ('is_current', models.BooleanField(default=False, verbose_name='année en cours')),
                ('is_locked', models.BooleanField(default=False, verbose_name='clôturée (lecture seule)')),
                ('opening_balances', models.JSONField(blank=True, default=dict, verbose_name="soldes d'ouverture")),
                ('note', models.TextField(blank=True, verbose_name='note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Année scolaire',
                'verbose_name_plural': 'Années scolaires',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('values', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Réglages',
                'verbose_name_plural': 'Réglages',
            },
        ),
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=core.models.new_intervention_code, max_length=32, unique=True, verbose_name='code')),
                ('token', models.TextField(blank=True, verbose_name='jeton signé')),
                ('action', models.CharField(max_length=32, verbose_name='action')),
                ('target', models.EmailField(blank=True, max_length=254, verbose_name='cible')),
                ('reason', models.CharField(blank=True, max_length=240, verbose_name='motif')),
                ('status', models.CharField(choices=[('queued', 'en attente'), ('delivered', 'délivrée'), ('applied', 'appliquée'), ('revoked', 'révoquée'), ('failed', 'échouée')], default='queued', max_length=16, verbose_name='état')),
                ('result', models.TextField(blank=True, verbose_name='résultat')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('origin', models.CharField(choices=[('hub', 'Hub'), ('token', 'Jeton hors ligne'), ('cli', 'CLI')], default='hub', max_length=8, verbose_name='origine')),
                ('applied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Intervention technique',
                'verbose_name_plural': 'Interventions techniques',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('mentions', 'Mentions légales'), ('rgpd', 'Données personnelles (RGPD)'), ('reglement', 'Règlement intérieur'), ('charte', "Charte d'utilisation")], max_length=20, verbose_name='type')),
                ('title', models.CharField(max_length=120, verbose_name='titre')),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('body', models.TextField(blank=True, verbose_name='contenu Markdown')),
                ('version', models.PositiveIntegerField(default=1)),
                ('requires_acceptance', models.BooleanField(default=False, verbose_name='acceptation obligatoire')),
                ('published', models.BooleanField(default=True, verbose_name='publié')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Texte légal',
                'verbose_name_plural': 'Textes légaux',
                'ordering': ['kind'],
            },
        ),
        migrations.CreateModel(
            name='ClosureDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(verbose_name='jour')),
                ('reason', models.CharField(blank=True, max_length=120, verbose_name='motif')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closure_days', to='core.schoolyear')),
            ],
            options={
                'verbose_name': 'Jour de fermeture',
                'verbose_name_plural': 'Jours de fermeture',
                'ordering': ['day'],
                'unique_together': {('year', 'day')},
            },
        ),
    ]
