# Generated by Django 5.2.17 on 2026-09-20 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HubInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120, verbose_name='nom')),
                ('url', models.CharField(blank=True, max_length=200, verbose_name='adresse')),
                ('install_id', models.CharField(max_length=64, unique=True, verbose_name="identifiant d'installation")),
                ('secret', models.CharField(max_length=128, verbose_name='secret partagé')),
                ('counters', models.JSONField(blank=True, default=dict, verbose_name='compteurs')),
                ('version', models.CharField(blank=True, max_length=20, verbose_name='version')),
                ('last_ping_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Instance raccordée',
                'verbose_name_plural': 'Instances raccordées',
                'ordering': ['label'],
            },
        ),
    ]
