# Generated by Django 5.2.17 on 2026-09-20 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_hubinstance'),
    ]

    operations = [
        migrations.AddField(
            model_name='installation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='installation',
            name='grace_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name="déblocage hors ligne valable jusqu'au"),
        ),
        migrations.AddField(
            model_name='installation',
            name='lock_reason',
            field=models.CharField(blank=True, max_length=240, verbose_name='motif de verrouillage'),
        ),
        migrations.AddField(
            model_name='installation',
            name='locked',
            field=models.BooleanField(default=False, verbose_name='verrouillée par la centrale'),
        ),
    ]
