# Generated by Django 5.2.17 on 2026-09-20 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_installation_created_at_installation_grace_until_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hubinstance',
            name='pending_actions',
            field=models.JSONField(blank=True, default=list, verbose_name='ordres en attente de livraison'),
        ),
    ]
