# Generated by Django 5.2.17 on 2026-09-20 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_hubinstance_pending_actions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HubInstance',
        ),
    ]
