# Generated by Django 5.2.17 on 2026-09-16 12:03

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='nom')),
                ('type', models.CharField(choices=[('bank', 'Compte bancaire'), ('safe', 'Coffre-fort'), ('other', 'Autre')], default='bank', max_length=8, verbose_name='type')),
                ('bank', models.CharField(blank=True, max_length=120, verbose_name='banque')),
                ('number', models.CharField(blank=True, max_length=60, verbose_name='numéro')),
                ('iban', models.CharField(blank=True, max_length=40, verbose_name='IBAN')),
                ('order', models.PositiveIntegerField(default=100, verbose_name='ordre')),
                ('active', models.BooleanField(default=True, verbose_name='actif')),
                ('is_safe', models.BooleanField(default=False, verbose_name='coffre (solde calculé)')),
                ('note', models.CharField(blank=True, max_length=240, verbose_name='note')),
            ],
            options={
                'verbose_name': 'Compte',
                'verbose_name_plural': 'Comptes',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BalanceRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('up_to_month', models.PositiveSmallIntegerField(default=1, verbose_name="mois d'arrêt")),
                ('auto', models.BooleanField(default=False, verbose_name='généré par le cron')),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('months', models.JSONField(blank=True, default=list, verbose_name='mois inclus')),
                ('stats', models.JSONField(blank=True, default=dict, verbose_name='statistiques')),
                ('status', models.CharField(choices=[('ok', 'généré'), ('partial', 'partiel'), ('failed', 'échoué')], default='ok', max_length=10, verbose_name='état')),
                ('message', models.CharField(blank=True, max_length=240, verbose_name='message')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('workbook', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='documents.document')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_runs', to='core.schoolyear')),
            ],
            options={
                'verbose_name': 'Génération de bilan',
                'verbose_name_plural': 'Générations de bilan',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120, verbose_name='libellé')),
                ('code', models.CharField(blank=True, max_length=20, verbose_name='code')),
                ('kind', models.CharField(choices=[('D', 'Dépense'), ('R', 'Recette')], default='D', max_length=1, verbose_name='sens')),
                ('color', models.CharField(default='#33556e', max_length=9, verbose_name='couleur')),
                ('order', models.PositiveIntegerField(default=100, verbose_name='ordre')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('note', models.CharField(blank=True, max_length=240, verbose_name='note')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='finance.category')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['kind', 'order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(db_index=True, verbose_name='date')),
                ('title', models.CharField(max_length=200, verbose_name='libellé')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='montant')),
                ('kind', models.CharField(choices=[('D', 'Dépense'), ('R', 'Recette'), ('T', 'Transfert interne'), ('A', "Ajustement d'écart")], db_index=True, default='D', max_length=1, verbose_name='sens')),
                ('mode', models.CharField(blank=True, choices=[('especes', 'Espèces'), ('cheque', 'Chèque'), ('virement', 'Virement'), ('prelevement', 'Prélèvement'), ('carte', 'Carte'), ('cheques-vacances', 'Chèques-vacances'), ('autre', 'Autre')], max_length=20, verbose_name='mode de règlement')),
                ('third_party', models.CharField(blank=True, max_length=160, verbose_name='tiers')),
                ('reference', models.CharField(blank=True, max_length=80, verbose_name='référence de pièce')),
                ('note', models.TextField(blank=True, verbose_name='note')),
                ('support_file', models.FileField(blank=True, upload_to='finance/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'png', 'jpg', 'jpeg', 'webp'])], verbose_name='justificatif')),
                ('safe_movement', models.CharField(blank=True, choices=[('in', 'Argent mis dans le coffre'), ('bank', 'Dépôt à la banque'), ('misc', 'Autre mouvement')], max_length=6, verbose_name='mouvement de coffre')),
                ('source', models.CharField(choices=[('manuel', 'Saisie manuelle'), ('import', 'Import'), ('coffre', 'Coffre'), ('reglage', 'Régularisation')], default='manuel', max_length=10, verbose_name='origine')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delete_reason', models.CharField(blank=True, max_length=240, verbose_name='motif de suppression')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='finance.account', verbose_name='compte')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='finance.category', verbose_name='catégorie')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to=settings.AUTH_USER_MODEL)),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_entries', to='finance.category', verbose_name='sous-catégorie')),
                ('support_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='documents.document')),
                ('to_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming', to='finance.account', verbose_name='compte destinataire')),
                ('transferred_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_pair', to='finance.entry')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='core.schoolyear')),
            ],
            options={
                'verbose_name': 'Écriture',
                'verbose_name_plural': 'Écritures',
                'ordering': ['-day', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CashCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(verbose_name='date')),
                ('expected', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=11, verbose_name='théorique')),
                ('counted', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=11, verbose_name='compté')),
                ('reason', models.CharField(blank=True, max_length=240, verbose_name="motif de l'écart")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_counts', to='finance.account')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_counts', to='core.schoolyear')),
                ('adjustment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='finance.entry')),
            ],
            options={
                'verbose_name': 'Comptage de caisse',
                'verbose_name_plural': 'Comptages de caisse',
                'ordering': ['-day'],
            },
        ),
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=240, verbose_name='fichier')),
                ('rows_total', models.PositiveIntegerField(default=0)),
                ('rows_created', models.PositiveIntegerField(default=0)),
                ('rows_skipped', models.PositiveIntegerField(default=0)),
                ('rows_error', models.PositiveIntegerField(default=0)),
                ('report', models.JSONField(blank=True, default=list, verbose_name='rapport')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reverted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reverted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_batches', to='core.schoolyear')),
            ],
            options={
                'verbose_name': 'Import',
                'verbose_name_plural': 'Imports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='entry',
            name='import_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='finance.importbatch'),
        ),
        migrations.CreateModel(
            name='MonthLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField(choices=[('9', 'septembre'), ('10', 'octobre'), ('11', 'novembre'), ('12', 'décembre'), ('1', 'janvier'), ('2', 'février'), ('3', 'mars'), ('4', 'avril'), ('5', 'mai'), ('6', 'juin'), ('7', 'juillet'), ('8', 'août')], verbose_name='mois')),
                ('year_number', models.PositiveIntegerField(verbose_name='année civile')),
                ('locked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.CharField(blank=True, max_length=240, verbose_name='note')),
                ('balance_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='documents.document')),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='month_locks', to='core.schoolyear')),
            ],
            options={
                'verbose_name': 'Clôture mensuelle',
                'verbose_name_plural': 'Clôtures mensuelles',
                'ordering': ['-year_number', '-month'],
                'unique_together': {('year', 'month', 'year_number')},
            },
        ),
        migrations.AddField(
            model_name='entry',
            name='month_lock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='finance.monthlock'),
        ),
        migrations.CreateModel(
            name='AccountOpening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=11, verbose_name='montant')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='openings', to='finance.account')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='openings', to='core.schoolyear')),
            ],
            options={
                'verbose_name': "Solde d'ouverture",
                'verbose_name_plural': "Soldes d'ouverture",
                'unique_together': {('year', 'account')},
            },
        ),
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['year', 'day', 'kind'], name='finance_ent_year_id_6fe196_idx'),
        ),
    ]
