# Generated by Django 5.2.17 on 2026-09-16 12:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=140, verbose_name='libellé')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('week', models.CharField(choices=[('Q1', 'Premier trimestre'), ('Q2', 'Deuxième trimestre'), ('Q3', 'Troisième trimestre'), ('AN', 'Année entière')], default='Q1', max_length=2, verbose_name='période')),
                ('start_date', models.DateField(verbose_name='début de la semaine')),
                ('end_date', models.DateField(verbose_name='fin de la semaine')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='date limite de réponse')),
                ('published', models.BooleanField(default=False, verbose_name='publiée')),
                ('closed', models.BooleanField(default=False, verbose_name='clôturée')),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='rappel envoyé le')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chore_campaigns', to='core.schoolyear')),
            ],
            options={
                'verbose_name': 'Campagne de ménage',
                'verbose_name_plural': 'Campagnes de ménage',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.CharField(choices=[('Q1', 'Premier trimestre'), ('Q2', 'Deuxième trimestre'), ('Q3', 'Troisième trimestre'), ('AN', 'Année entière')], default='Q1', max_length=2, verbose_name='semaine')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(1, 'lundi'), (2, 'mardi'), (3, 'mercredi'), (4, 'jeudi'), (5, 'vendredi'), (6, 'samedi'), (0, 'dimanche')], default=1, verbose_name='jour')),
                ('zone', models.CharField(default='Local MDL', max_length=120, verbose_name='lieu')),
                ('task', models.CharField(max_length=160, verbose_name='tâche')),
                ('status', models.CharField(choices=[('todo', 'à faire'), ('done', 'fait, à valider'), ('validated', 'validé'), ('redo', 'à refaire')], db_index=True, default='todo', max_length=10, verbose_name='état')),
                ('done_at', models.DateTimeField(blank=True, null=True, verbose_name='fait le')),
                ('proof', models.FileField(blank=True, upload_to='menage/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'gif'])], verbose_name='photo de preuve')),
                ('note', models.CharField(blank=True, max_length=240, verbose_name='note')),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chore_assignments', to=settings.AUTH_USER_MODEL)),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='chores.campaign')),
            ],
            options={
                'verbose_name': 'Tâche de ménage',
                'verbose_name_plural': 'Tâches de ménage',
                'ordering': ['weekday', 'member__last_name'],
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(choices=[('accept', "J'accepte"), ('decline', 'Je ne peux pas')], default='accept', max_length=8, verbose_name='réponse')),
                ('note', models.CharField(blank=True, max_length=240, verbose_name='note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='chores.campaign')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chore_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Réponse de ménage',
                'verbose_name_plural': 'Réponses de ménage',
                'unique_together': {('campaign', 'member')},
            },
        ),
    ]
