# Generated by Django 5.2.17 on 2026-09-19 09:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=160, verbose_name='tâche')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(1, 'lundi'), (2, 'mardi'), (3, 'mercredi'), (4, 'jeudi'), (5, 'vendredi'), (6, 'samedi'), (0, 'dimanche')], default=1, verbose_name='jour')),
                ('zone', models.CharField(default='Local MDL', max_length=120, verbose_name='lieu')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='chores.campaign')),
            ],
            options={
                'verbose_name': 'Tâche de campagne',
                'verbose_name_plural': 'Tâches de campagne',
                'ordering': ['weekday', 'label'],
            },
        ),
        migrations.AddField(
            model_name='assignment',
            name='task_def',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='chores.task', verbose_name='tâche de campagne'),
        ),
        migrations.CreateModel(
            name='ChorePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.CharField(blank=True, max_length=20, verbose_name='jours disponibles')),
                ('refused', models.TextField(blank=True, verbose_name='tâches refusées')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='chores.campaign')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chore_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Préférence de ménage',
                'verbose_name_plural': 'Préférences de ménage',
                'unique_together': {('campaign', 'member')},
            },
        ),
    ]
