# Generated by Django 5.2.17 on 2026-09-16 12:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=140, verbose_name='libellé')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('week', models.CharField(choices=[('Q1', 'Premier trimestre'), ('Q2', 'Deuxième trimestre'), ('Q3', 'Troisième trimestre'), ('S1', 'Premier semestre'), ('S2', 'Second semestre'), ('AN', 'Année entière')], default='Q1', max_length=2, verbose_name='période')),
                ('start_date', models.DateField(verbose_name='ouverture')),
                ('end_date', models.DateField(verbose_name='clôture des réponses')),
                ('slot_duration', models.PositiveSmallIntegerField(default=60, verbose_name="durée d'un créneau (minutes)")),
                ('published', models.BooleanField(default=False, verbose_name='publiée')),
                ('closed', models.BooleanField(default=False, verbose_name='clôturée')),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='rappel envoyé le')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planning_campaigns', to='core.schoolyear')),
            ],
            options={
                'verbose_name': 'Campagne de disponibilités',
                'verbose_name_plural': 'Campagnes de disponibilités',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(1, 'lundi'), (2, 'mardi'), (3, 'mercredi'), (4, 'jeudi'), (5, 'vendredi'), (6, 'samedi'), (0, 'dimanche')], verbose_name='jour')),
                ('start_time', models.TimeField(verbose_name='début')),
                ('end_time', models.TimeField(verbose_name='fin')),
                ('capacity', models.PositiveSmallIntegerField(default=1, verbose_name='nombre de gérants')),
                ('label', models.CharField(blank=True, help_text='Ex. : permanence midi, ouverture du foyer.', max_length=140, verbose_name='intitulé')),
                ('order', models.PositiveIntegerField(default=100, verbose_name='ordre')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='plannings.campaign')),
            ],
            options={
                'verbose_name': 'Créneau',
                'verbose_name_plural': 'Créneaux',
                'ordering': ['weekday', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(choices=[('yes', 'Disponible'), ('maybe', 'Si besoin'), ('no', 'Indisponible')], default='yes', max_length=6, verbose_name='réponse')),
                ('note', models.CharField(blank=True, max_length=240, verbose_name='note')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to=settings.AUTH_USER_MODEL)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='plannings.campaign')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='plannings.slot')),
            ],
            options={
                'verbose_name': 'Disponibilité',
                'verbose_name_plural': 'Disponibilités',
                'ordering': ['slot__weekday', 'slot__start_time'],
                'unique_together': {('campaign', 'member', 'slot')},
            },
        ),
    ]
