# Generated by Django 5.2.17 on 2026-09-16 11:33

import accounts.managers
import accounts.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(db_index=True, max_length=190, unique=True, verbose_name='e-mail')),
                ('first_name', models.CharField(blank=True, max_length=80, verbose_name='prénom')),
                ('last_name', models.CharField(blank=True, max_length=80, verbose_name='nom')),
                ('display_function', models.CharField(blank=True, max_length=120, verbose_name='fonction affichée')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='téléphone')),
                ('gender', models.CharField(blank=True, choices=[('f', 'elle'), ('m', 'il'), ('n', 'neutre')], max_length=1, verbose_name='mention')),
                ('photo', models.FileField(blank=True, upload_to='avatars/%Y/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'webp', 'gif'])], verbose_name='photo')),
                ('status', models.CharField(choices=[('pending', "en attente d'invitation"), ('active', 'actif'), ('inactive', 'inactif'), ('anonymized', 'anonymisé')], default='pending', max_length=12, verbose_name='statut')),
                ('is_boarder', models.BooleanField(default=False, verbose_name='interne (hébergement au lycée)')),
                ('totp_secret', models.CharField(blank=True, max_length=64, verbose_name='clé A2F')),
                ('totp_enabled', models.BooleanField(default=False, verbose_name='A2F activée')),
                ('totp_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('must_change_password', models.BooleanField(default=False, verbose_name='doit changer son mot de passe')),
                ('must_accept_charte', models.BooleanField(default=False, verbose_name='doit accepter la charte')),
                ('failed_logins', models.PositiveSmallIntegerField(default=0, verbose_name='tentatives échouées')),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True, verbose_name='dernière activité')),
                ('prefs', models.JSONField(blank=True, default=dict, verbose_name='préférences')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Membre',
                'verbose_name_plural': 'Membres',
                'ordering': ['last_name', 'first_name'],
            },
            managers=[
                ('objects', accounts.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='LegalAcceptance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=1)),
                ('accepted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Acceptation',
                'verbose_name_plural': 'Acceptations',
                'ordering': ['-accepted_at'],
            },
        ),
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=240)),
                ('success', models.BooleanField(default=False)),
                ('reason', models.CharField(blank=True, max_length=120, verbose_name='motif')),
                ('at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Tentative de connexion',
                'verbose_name_plural': 'Tentatives de connexion',
                'ordering': ['-at'],
            },
        ),
        migrations.CreateModel(
            name='RecoveryCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Code de récupération',
                'verbose_name_plural': 'Codes de récupération',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='nom')),
                ('slug', models.SlugField(blank=True, max_length=90, unique=True)),
                ('description', models.CharField(blank=True, max_length=240, verbose_name='description')),
                ('color', models.CharField(default='#33556e', max_length=9, verbose_name='couleur')),
                ('icon', models.CharField(default='user', max_length=24, verbose_name='icône')),
                ('is_administrator', models.BooleanField(default=False, verbose_name='rôle Administrateur')),
                ('is_system', models.BooleanField(default=False, verbose_name='rôle système (protégé)')),
                ('is_default', models.BooleanField(default=False, verbose_name='rôle par défaut')),
                ('force_2fa', models.BooleanField(default=False, verbose_name="imposer l'A2F")),
                ('force_2fa_deadline_days', models.PositiveIntegerField(default=14, verbose_name="délai d'activation (jours)")),
                ('fine_permissions', models.JSONField(blank=True, default=list, verbose_name='droits fins')),
                ('home', models.CharField(choices=[('dashboard', 'Tableau de bord'), ('planning', 'Mon planning'), ('documents', 'Documents'), ('messages', 'Messages')], default='dashboard', max_length=16, verbose_name="écran d'accueil")),
                ('order', models.PositiveIntegerField(default=100, verbose_name='ordre')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Rôle',
                'verbose_name_plural': 'Rôles',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RoleMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('since', models.DateTimeField(default=django.utils.timezone.now)),
                ('until', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Historique de rôle',
                'verbose_name_plural': 'Historiques de rôle',
                'ordering': ['-since'],
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.CharField(choices=[('dashboard', 'Tableau de bord'), ('members', 'Membres & invitations'), ('roles', 'Rôles & droits'), ('documents', 'Documents'), ('finance', 'Trésorerie'), ('planning_salle', 'Planning de la salle'), ('planning_menage', 'Planning de ménage'), ('mail', 'Messagerie interne'), ('audit', "Journal d'audit"), ('backup', 'Sauvegarde & restauration'), ('settings_global', "Réglages de l'association")], max_length=32, verbose_name='module')),
                ('level', models.PositiveSmallIntegerField(choices=[(0, 'Aucun'), (1, 'Consulter'), (2, 'Modifier')], default=0, verbose_name='niveau')),
            ],
            options={
                'verbose_name': 'Droit de module',
                'verbose_name_plural': 'Droits de module',
            },
        ),
        migrations.CreateModel(
            name='UserProfileExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('promotion', models.CharField(blank=True, max_length=20, verbose_name='promotion')),
                ('since_year', models.CharField(blank=True, max_length=12, verbose_name='membre depuis')),
            ],
            options={
                'verbose_name': 'Complément de fiche',
                'verbose_name_plural': 'Compléments de fiche',
            },
        ),
        migrations.CreateModel(
            name='AccountSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=64, unique=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=240)),
                ('device', models.CharField(blank=True, max_length=120, verbose_name='appareil')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_pwa', models.BooleanField(default=False, verbose_name='installée (PWA)')),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Session',
                'verbose_name_plural': 'Sessions',
                'ordering': ['-last_seen'],
            },
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=accounts.models.new_token, editable=False, unique=True)),
                ('code', models.CharField(blank=True, max_length=6, unique=True, verbose_name='code court')),
                ('message', models.TextField(blank=True, verbose_name="message d'accompagnement")),
                ('channel', models.CharField(choices=[('email', 'E-mail'), ('manual', 'Transmis à la main'), ('both', 'Les deux')], default='email', max_length=8, verbose_name='canal')),
                ('expires_at', models.DateTimeField(verbose_name='expire le')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('delivered', models.BooleanField(default=False, verbose_name='transmise')),
                ('reminded_at', models.DateTimeField(blank=True, null=True)),
                ('reminder_count', models.PositiveSmallIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invitation', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Invitation',
                'verbose_name_plural': 'Invitations',
                'ordering': ['-created_at'],
            },
        ),
    ]
