# Generated by Django 5.2.17 on 2026-09-16 11:57

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='nom')),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('description', models.CharField(blank=True, max_length=240, verbose_name='description')),
                ('color', models.CharField(default='#33556e', max_length=9, verbose_name='couleur')),
                ('icon', models.CharField(default='folder', max_length=24, verbose_name='icône')),
                ('order', models.PositiveIntegerField(default=100, verbose_name='ordre')),
                ('locked_read', models.BooleanField(default=False, verbose_name='verrouillée en lecture')),
                ('archived', models.BooleanField(default=False, verbose_name='archivée')),
                ('allow_download', models.BooleanField(default=True, verbose_name='téléchargement autorisé')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='titre')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='étiquettes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('locked', models.BooleanField(default=False, verbose_name='verrouillé')),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('downloads', models.PositiveIntegerField(default=0)),
                ('views', models.PositiveIntegerField(default=0)),
                ('offline_cacheable', models.BooleanField(default=True, verbose_name='consultable hors ligne')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('delete_reason', models.CharField(blank=True, max_length=240, verbose_name='motif de suppression')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='documents.category')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'xls', 'xlsx', 'ods', 'odt', 'odp', 'png', 'jpg', 'jpeg', 'webp', 'gif', 'txt', 'csv', 'zip'])])),
                ('original_name', models.CharField(blank=True, max_length=240, verbose_name="nom d'origine")),
                ('ext', models.CharField(blank=True, max_length=12, verbose_name='extension')),
                ('size', models.PositiveIntegerField(default=0, verbose_name='taille (octets)')),
                ('sha256', models.CharField(blank=True, max_length=64, verbose_name='empreinte')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='version')),
                ('comment', models.CharField(blank=True, max_length=240, verbose_name='commentaire')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_current', models.BooleanField(default=False, verbose_name='version courante')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='documents.document')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Version de document',
                'verbose_name_plural': 'Versions de document',
                'ordering': ['-version'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='current',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='documents.documentfile'),
        ),
        migrations.CreateModel(
            name='DocumentViewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('view', 'consultation'), ('download', 'téléchargement')], max_length=12, verbose_name='action')),
                ('at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_logs', to='documents.document')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Consultation',
                'verbose_name_plural': 'Consultations',
                'ordering': ['-at'],
            },
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, verbose_name='nom')),
                ('description', models.CharField(blank=True, max_length=240, verbose_name='description')),
                ('locked_read', models.BooleanField(default=False, verbose_name='verrouillé en lecture')),
                ('order', models.PositiveIntegerField(default=100, verbose_name='ordre')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='documents.category')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='documents.folder')),
            ],
            options={
                'verbose_name': 'Dossier',
                'verbose_name_plural': 'Dossiers',
                'ordering': ['order', 'name'],
                'unique_together': {('category', 'parent', 'name')},
            },
        ),
        migrations.AddField(
            model_name='document',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='documents.folder'),
        ),
        migrations.CreateModel(
            name='CategoryAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(choices=[(0, 'Aucun'), (1, 'Consulter'), (2, 'Modifier')], default=1, verbose_name='niveau')),
                ('can_delete', models.BooleanField(default=False, verbose_name='peut supprimer')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesses', to='documents.category')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_accesses', to='accounts.role')),
            ],
            options={
                'verbose_name': 'Accès à une catégorie',
                'verbose_name_plural': 'Accès aux catégories',
                'unique_together': {('category', 'role')},
            },
        ),
    ]
