# Generated by Django 5.2.17 on 2026-09-17 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='module_gate',
            field=models.CharField(blank=True, help_text="Laisse vide pour n'exiger que le module Documents. Renseigner « finance » restreint la catégorie aux membres qui peuvent consulter la trésorerie.", max_length=30, verbose_name='module requis'),
        ),
    ]
