# Generated by Django 5.2.17 on 2026-09-16 12:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Broadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=160, verbose_name='objet')),
                ('body', models.TextField(help_text='Markdown léger accepté.', verbose_name='message')),
                ('kind', models.CharField(choices=[('info', 'Information'), ('important', 'Important'), ('alert', 'Alerte'), ('bilan', 'Bilan'), ('planning', 'Planning'), ('menage', 'Ménage'), ('technique', 'Technique')], default='info', max_length=10, verbose_name='type')),
                ('audience', models.CharField(choices=[('all', 'Tous les membres actifs'), ('board', 'Bureau uniquement'), ('role', 'Rôles choisis'), ('manual', 'Liste manuelle')], default='all', max_length=8, verbose_name='destinataires')),
                ('requires_ack', models.BooleanField(default=False, verbose_name='accusé de lecture demandé')),
                ('notify_email', models.BooleanField(default=True, verbose_name='doublé par courriel')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='envoi programmé')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='envoyé le')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('scheduled', 'Programmé'), ('sent', 'Envoyé'), ('cancelled', 'Annulé')], db_index=True, default='draft', max_length=10, verbose_name='état')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broadcasts', to=settings.AUTH_USER_MODEL)),
                ('roles', models.ManyToManyField(blank=True, related_name='broadcasts', to='accounts.role')),
            ],
            options={
                'verbose_name': 'Diffusion',
                'verbose_name_plural': 'Diffusions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Outbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_email', models.EmailField(max_length=254, verbose_name='destinataire')),
                ('subject', models.CharField(max_length=200, verbose_name='objet')),
                ('text_body', models.TextField(verbose_name='corps texte')),
                ('kind', models.CharField(blank=True, max_length=20, verbose_name='type')),
                ('urgent', models.BooleanField(default=False, verbose_name='urgent')),
                ('status', models.CharField(choices=[('queued', 'En attente'), ('sent', 'Envoyé'), ('failed', 'Échec'), ('skipped', 'Ignoré')], db_index=True, default='queued', max_length=8, verbose_name='état')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='tentatives')),
                ('error', models.CharField(blank=True, max_length=400, verbose_name='erreur')),
                ('queued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('recipient_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Courriel en attente',
                'verbose_name_plural': 'Courriels en attente',
                'ordering': ['-urgent', 'queued_at'],
            },
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='lu le')),
                ('ack_at', models.DateTimeField(blank=True, null=True, verbose_name='accusé le')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='archivé le')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('broadcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='mail.broadcast')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Destinataire',
                'verbose_name_plural': 'Destinataires',
                'ordering': ['-created_at'],
                'unique_together': {('broadcast', 'user')},
            },
        ),
    ]
