# Generated by Django 5.2.17 on 2026-09-18 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outbox',
            name='status',
            field=models.CharField(choices=[('queued', 'En attente'), ('sending', 'En cours'), ('sent', 'Envoyé'), ('failed', 'Échec'), ('skipped', 'Ignoré')], db_index=True, default='queued', max_length=8, verbose_name='état'),
        ),
    ]
