# Generated by Django 5.2.17 on 2026-09-16 11:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PushDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.URLField(max_length=500, unique=True)),
                ('keys', models.JSONField(blank=True, default=dict, verbose_name='clés p256dh / auth')),
                ('ua', models.CharField(blank=True, max_length=240, verbose_name='navigateur')),
                ('label', models.CharField(blank=True, max_length=80, verbose_name='étiquette')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_success', models.DateTimeField(blank=True, null=True)),
                ('failures', models.PositiveSmallIntegerField(default=0)),
                ('disabled', models.BooleanField(default=False, verbose_name='désactivé')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Appareil abonné',
                'verbose_name_plural': 'Appareils abonnés',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(db_index=True, max_length=32, verbose_name='événement')),
                ('title', models.CharField(max_length=160, verbose_name='titre')),
                ('body', models.TextField(blank=True, verbose_name='corps')),
                ('url', models.CharField(blank=True, max_length=240, verbose_name='lien profond')),
                ('level', models.CharField(choices=[('info', 'info'), ('success', 'succès'), ('warning', 'avertissement'), ('danger', 'danger')], default='info', max_length=8, verbose_name='niveau')),
                ('email_sent', models.BooleanField(default=False, verbose_name='e-mail envoyé')),
                ('push_sent', models.BooleanField(default=False, verbose_name='push envoyé')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['user', 'read_at'], name='notificatio_user_id_47e85c_idx')],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=32, verbose_name='événement')),
                ('inapp', models.BooleanField(blank=True, default=None, null=True, verbose_name="dans l'app")),
                ('email', models.BooleanField(blank=True, default=None, null=True, verbose_name='e-mail')),
                ('push', models.BooleanField(blank=True, default=None, null=True, verbose_name='push')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_prefs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Préférence de notification',
                'verbose_name_plural': 'Préférences de notification',
                'unique_together': {('user', 'kind')},
            },
        ),
    ]
